---
title: "About this study"
---

## **From reanalysis data to inference: a framework for linking environment to plant disease epidemics at the regional scale**

**Kaique S. Alves^1,2^; Denis A. Shah^3^; Helene. R. Dillard^4^; Emerson M. Del Ponte^1^; Sarah J. Pethybridge^2\*^**

> ^**1**^ Departamento de Fitopatologia, Universidade Federal de Viçosa, Viçosa, MG 36570-900, Brazil
>
> ^**2**^ Plant Pathology & Plant-Microbe Biology Section, School of Integrative Plant Science, Cornell University, Geneva, NY 14456, USA
>
> ^**3**^ Department of Plant Pathology, Kansas State University, Manhattan, KS 66506, USA
>
> ^**4**^ College of Agricultural and Environmental Sciences, University of California, Davis, CA 95616, USA
>
> \***Corresponding author**: Sarah. J. Pethybridge
>
> **Email**: sjp277\@cornell.edu



## Summary

We propose and demonstrate a complete framework for the fusion of environmental data with observations of plant disease at the regional scale. The standard on-ground weather station network is often too sparse relative to the scale of agricultural fields to make use of an in-depth study of the relationship between weather and disease, and results in observational datasets are hence unused or under-utilized. Our work shows how environmental data can be obtained online and downscaled to the field level. We then show how potential predictor variables can be identified in downscaled weather time series. Our final step uses these predictors to fit and interpret a  machine learning model to understand how weather contributes to plant disease risk. Our case study was white mold of snap beans, and the results have identified new avenues of research in disease risk modeling. We believe that the proposed framework is broadly applicable to any ecological field.

## Original article

::: {.callout-note appearance="simple"}
# This [repository](https://osf.io/v53py/){target="_blank"} contains the data and code for our article:

Alves, K.S., Shah, D.A., Dillard, H.R., Del Ponte, E.M., Pethybridge, S.J. (YYYY) From reanalysis data to inference: a framework for linking environment to plant disease epidemics at the regional scale .Name of journal/book <https://doi.org/xxx/xxx>
:::

## Read the Preprint

::: {.callout-note appearance="simple"}
# Our pre-print is online on the OSF preprint server:

Alves, K.S., Shah, D.A., Dillard, H.R., Del Ponte, E.M., Pethybridge, S.J. (YYYY) From reanalysis data to inference: a framework for linking environment to plant disease epidemics at the regional scale. OSF, Accessed 23 June 2022. Online at <https://doi.org/xxx/xxx>
:::

## Research compendium

::: {.callout-note appearance="simple"}
## Please cite this research compendium as:

Alves, K. S., Shah, D. A., Dillard, H. R., Del Ponte, E. M., & Pethybridge, S. J. (2022, August 3). Research Compendium: From reanalysis data to inference: a framework for linking environment to plant disease epidemics at the regional scale. https://doi.org/10.17605/OSF.IO/V53PY
:::






